AWSTemplateFormatVersion: 2010-09-09
Description: Security Group module - Public and Private EC2 Security Groups

Parameters:
  ProjectName:
    Type: String
  VpcId:
    Type: AWS::EC2::VPC::Id
  MyIp:
    Type: String
    Description: Your public IP address (without /32)

Resources:
  PublicEC2SG:
    Type: AWS::EC2::SecurityGroup
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      GroupName:
        Fn::Sub: "${ProjectName}-public-sg"
      GroupDescription: Allow SSH only from admin IP
      VpcId:
        Ref: VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp:
            Fn::Sub: "${MyIp}/32"
          Description: SSH from my IP only
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value:
            Fn::Sub: "${ProjectName}-public-sg"

  PrivateEC2SG:
    Type: AWS::EC2::SecurityGroup
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      GroupName:
        Fn::Sub: "${ProjectName}-private-sg"
      GroupDescription: Allow SSH only from Public EC2 Security Group
      VpcId:
        Ref: VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          SourceSecurityGroupId:
            Ref: PublicEC2SG
          Description: SSH from Public EC2 SG only
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value:
            Fn::Sub: "${ProjectName}-private-sg"

Outputs:
  PublicSGId:
    Value:
      Ref: PublicEC2SG
  PrivateSGId:
    Value:
      Ref: PrivateEC2SG